name: Build NASM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential automake libtool dpkg-dev wget

    - name: Install Autoconf 2.71
      run: |
        wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.gz
        tar -xf autoconf-2.71.tar.gz
        cd autoconf-2.71
        ./configure
        make
        sudo make install
        autoconf --version

    - name: Build NASM
      run: |
        ./autogen.sh
        ./configure
        make

    - name: Create DEB package
      run: |
        mkdir -p debian/DEBIAN
        mkdir -p debian/usr/local/bin
        cp nasm debian/usr/local/bin/
        
        # Create control file
        cat <<EOF > debian/DEBIAN/control
        Package: nasm
        Version: 2.15.05
        Section: devel
        Priority: optional
        Architecture: amd64
        Depends: libc6 (>= 2.14)
        Maintainer: Your Name <your.email@example.com>
        Description: NASM is an assembler for the x86 CPU architecture
        EOF

        # Build the package
        dpkg-deb --build debian nasm-2.15.05.deb

    - name: Upload DEB package
      uses: actions/upload-artifact@v2
      with:
        name: nasm-deb
        path: nasm-2.15.05.deb
